apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authwarden
  namespace: authwarden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - authwarden.example.com
      secretName: authwarden-tls
  rules:
    - host: authwarden.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authwarden
                port:
                  name: http
