apiVersion: v1
kind: Service
metadata:
  name: authwarden
  namespace: authwarden
  labels:
    app.kubernetes.io/name: authwarden
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: authwarden
  ports:
    - name: http
      port: 80
      targetPort: http
